name: Generate snake animation

on:
  schedule: # Executar a cada 12 horas
    - cron: "0 */12 * * *"

  workflow_dispatch: # Permitir execução manual do workflow

  push:
    branches:
      - master # Executar quando houver push na branch master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ramon-romano # Seu nome de usuário do GitHub

      - name: Criar diretório para o SVG
        run: mkdir -p dist

      - name: Mover snake.svg para o diretório dist
        run: mv snake.svg dist/snake.svg

      - name: Push snake.svg para o branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
